<MainGrid>

    message: message

    GridLayout:
        cols: 1
        size: root.width - 200, root.height - 200
        pos: 100, 100

        GridLayout:
            cols: 2

            Label:
                text: "Enter a message: "
            
            TextInput:
                id: message
                multiline: False
        
        Button:
            text: "Enter"
            on_press: root.enter_message()
